### ISSUE TITLE
S3 Download and Upload tasks fail without role after 1.2.0 update

### ISSUE THREAD

**Issue by jbaacke** [aws/aws-vsts-tools#246] opened 2019-06-12 18:44 UTC
**Describe the bug**
When running the "Amazon S3 Download" task with a AWS Credentials with an Access Key and Secret Key the task fails. I believe this is due to the task group attempting to assume a 

**To reproduce**
1. Create an AWS Credential service connector using only an access key and secret key. 
2. Create a pipeline task using the above credential to download an object from S3.
3. Run the pipeline stage containing the pipeline task created above. 
4. See the task fail stating the bucket does not exist. 

**Expected behavior**
Expected behaviour would be the object being downloaded from the targeted bucket. 

**Screenshots**

**Your Environment**
 - VSTS or Azure Devops (on-prem or cloud based?): Cloud
 - VSTS or Azure Devops version: Cloud
 - AWS VSTS Tools version: 1.2.0

**Additional context**
When I went in CloudTrail to monitor the usage of the access key associated with the service connector it has a series of denied requests to assume a role. I did not specify a target role in the service connector. An example event id is 974aa848-b6cc-492c-afb9-f39d0644beca

**Comment by anottest** [comment] 2019-06-12 18:51
I'm experiencing this issue as well. It has caused all the S3 tasks in my existing pipelines to start failing.

**Comment by whoiskevinrich** [comment] 2019-06-12 18:57
Also having this issue when attempting to deploy to elastic beanstalk

**Comment by daniloreis-cit** [comment] 2019-06-12 19:09
Having a similar problem with another task type.

**Comment by gholt-aws** [comment] 2019-06-12 19:15
We're taking a look right now...

**Comment by isiddiq3** [comment] 2019-06-12 19:26
System Manager Run command  Fails with AccessDeniedException after 1.2.0 release, the Assume Role has all the required permissions. The Same document Runs fine from the AWS console.

**Comment by hunterwerlla** [comment] 2019-06-12 19:35
Can you provide logs from azure devops, also what is your account configuration? one account or multiple accounts? Also, to confirm, this is the hosted version of azure devops?

**Comment by thepharcyde2016** [comment] 2019-06-12 19:40
yes we are having a similar issue since the version 1.2.0 was rolled out. The AWS CloudFormation Create/Update Stack
cannot seem to pull the Aws credentials.  This is the error we are getting.  
2019-06-12T18:14:39.1597700Z Change set creation request failed with error: 'Missing credentials in config' { CredentialsError: Missing credentials in config
2019-06-12T18:14:39.1597700Z     at IncomingMessage.<anonymous> (F:\_a\1\_w\_tasks\CloudFormationCreateOrUpdateStack_7ef7cdfa-aa45-42c5-93c8-d7603643dd99\1.2.0\CloudFormationCreateOrUpdateStack.js:1:16536)
2019-06-12T18:14:39.1597700Z     at emitNone (events.js:91:20)
2019-06-12T18:14:39.1597700Z     at IncomingMessage.emit (events.js:185:7)
2019-06-12T18:14:39.1597700Z     at endReadableNT (_stream_readable.js:974:12)
2019-06-12T18:14:39.1597700Z     at _combinedTickCallback (internal/process/next_tick.js:80:11)
2019-06-12T18:14:39.1597700Z     at process._tickDomainCallback (internal/process/next_tick.js:128:9)
2019-06-12T18:14:39.1597700Z   message: 'Missing credentials in config',
2019-06-12T18:14:39.1597700Z   retryable: false,
2019-06-12T18:14:39.1597700Z   time: 2019-06-12T18:14:39.159Z,
2019-06-12T18:14:39.1597700Z   code: 'CredentialsError',
2019-06-12T18:14:39.1597700Z   originalError: 
2019-06-12T18:14:39.1597700Z    { message: 'Could not load credentials from any providers',
2019-06-12T18:14:39.1597700Z      retryable: false,
2019-06-12T18:14:39.1597700Z      time: 2019-06-12T18:14:39.159Z,
2019-06-12T18:14:39.1597700Z      code: 'CredentialsError' } }
2019-06-12T18:14:39.1753930Z ##[error]CredentialsError: Missing credentials in config

**Comment by jbaacke** [comment] 2019-06-12 19:43
Debug logs from upload task (bucket name was find and replaced with targetbucketobscured): 

2019-06-12T18:04:26.9977798Z ##[debug]Evaluating condition for step: 'S3 Download: targetbucketobscured'
2019-06-12T18:04:26.9978428Z ##[debug]Evaluating: succeeded()
2019-06-12T18:04:26.9978572Z ##[debug]Evaluating succeeded:
2019-06-12T18:04:26.9979063Z ##[debug]=> True
2019-06-12T18:04:26.9979319Z ##[debug]Result: True
2019-06-12T18:04:26.9979549Z ##[section]Starting: S3 Download: targetbucketobscured
2019-06-12T18:04:27.7707140Z ==============================================================================
2019-06-12T18:04:27.7707491Z Task         : Amazon S3 Download
2019-06-12T18:04:27.7707611Z Description  : Download file and folder content from an Amazon Simple Storage Service (S3) Bucket on AWS
2019-06-12T18:04:27.7707705Z Version      : 1.2.0
2019-06-12T18:04:27.7708813Z Author       : Amazon Web Services
2019-06-12T18:04:27.7709002Z Help         : Please refer to [Working with Amazon S3 Buckets](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html) for more information on working with Amazon S3.

More information on this task can be found in the [task reference](https://docs.aws.amazon.com/vsts/latest/userguide/s3-download.html).

####Task Permissions
This task requires permissions to call the following AWS service APIs (depending on selected task options, not all APIs may be used):
* s3:GetObject
* s3:HeadBucket
* s3:ListObjects
2019-06-12T18:04:27.7709199Z ==============================================================================
2019-06-12T18:04:28.4486074Z ##[debug]agent.TempDirectory=D:\a\_temp
2019-06-12T18:04:28.4486409Z ##[debug]loading inputs and endpoints
2019-06-12T18:04:28.4486636Z ##[debug]loading ENDPOINT_AUTH_5a441e49-72f1-447f-9c35-9bb7fcfb0426
2019-06-12T18:04:28.4486861Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_5a441e49-72f1-447f-9c35-9bb7fcfb0426_PASSWORD
2019-06-12T18:04:28.4487117Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_5a441e49-72f1-447f-9c35-9bb7fcfb0426_USERNAME
2019-06-12T18:04:28.4487331Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2019-06-12T18:04:28.4487544Z ##[debug]loading ENDPOINT_AUTH_SCHEME_5a441e49-72f1-447f-9c35-9bb7fcfb0426
2019-06-12T18:04:28.4487753Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2019-06-12T18:04:28.4487957Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2019-06-12T18:04:28.4488147Z ##[debug]loading INPUT_AWSCREDENTIALS
2019-06-12T18:04:28.4488428Z ##[debug]loading INPUT_BUCKETNAME
2019-06-12T18:04:28.4488616Z ##[debug]loading INPUT_FLATTENFOLDERS
2019-06-12T18:04:28.4488864Z ##[debug]loading INPUT_FORCEPATHSTYLEADDRESSING
2019-06-12T18:04:28.4489055Z ##[debug]loading INPUT_GLOBEXPRESSIONS
2019-06-12T18:04:28.4489243Z ##[debug]loading INPUT_KEYMANAGEMENT
2019-06-12T18:04:28.4489430Z ##[debug]loading INPUT_LOGREQUEST
2019-06-12T18:04:28.4489606Z ##[debug]loading INPUT_LOGRESPONSE
2019-06-12T18:04:28.4489809Z ##[debug]loading INPUT_OVERWRITE
2019-06-12T18:04:28.4489998Z ##[debug]loading INPUT_REGIONNAME
2019-06-12T18:04:28.4490509Z ##[debug]loading INPUT_SOURCEFOLDER
2019-06-12T18:04:28.4490725Z ##[debug]loading INPUT_TARGETFOLDER
2019-06-12T18:04:28.4490903Z ##[debug]loading SECRET_AWS_KEY_SECRETKEY
2019-06-12T18:04:28.4491103Z ##[debug]loading SECRET_TERRAFORMMODULELIBRARYSECRETKEY
2019-06-12T18:04:28.4491296Z ##[debug]loaded 21
2019-06-12T18:04:28.4491484Z ##[debug]Agent.ProxyUrl=undefined
2019-06-12T18:04:28.4491670Z ##[debug]Agent.CAInfo=undefined
2019-06-12T18:04:28.4491842Z ##[debug]Agent.ClientCert=undefined
2019-06-12T18:04:28.4492037Z ##[debug]Agent.SkipCertValidation=undefined
2019-06-12T18:04:28.4492246Z ##[debug]check path : D:\a\_tasks\S3Download_30f6a876-1d27-450c-b2bb-9f390a592082\1.2.0\task.json
2019-06-12T18:04:28.4492469Z ##[debug]adding resource file: D:\a\_tasks\S3Download_30f6a876-1d27-450c-b2bb-9f390a592082\1.2.0\task.json
2019-06-12T18:04:28.4492917Z ##[debug]system.culture=en-US
2019-06-12T18:04:28.4493112Z ##[debug]logRequest=false
2019-06-12T18:04:28.4493282Z ##[debug]logResponse=false
2019-06-12T18:04:28.4493465Z ##[debug]Agent.ProxyUrl=undefined
2019-06-12T18:04:28.4495399Z ##[debug]bucketName=targetbucketobscured
2019-06-12T18:04:28.4495658Z ##[debug]sourceFolder=RedLock/Prod
2019-06-12T18:04:28.4495838Z ##[debug]targetFolder=D:\a\r1\a
2019-06-12T18:04:28.4496031Z ##[debug]globExpressions=**.tfstate
2019-06-12T18:04:28.4496220Z ##[debug]overwrite=true
2019-06-12T18:04:28.4496406Z ##[debug]forcePathStyleAddressing=false
2019-06-12T18:04:28.4496594Z ##[debug]flattenFolders=true
2019-06-12T18:04:28.4496766Z ##[debug]keyManagement=noneOrAWSManaged
2019-06-12T18:04:28.4496916Z Configuring credentials for task
2019-06-12T18:04:28.4497077Z ##[debug]awsCredentials=5a441e49-72f1-447f-9c35-9bb7fcfb0426
2019-06-12T18:04:28.4497164Z 5a441e49-72f1-447f-9c35-9bb7fcfb0426 exists true
2019-06-12T18:04:28.4497368Z ##[debug]5a441e49-72f1-447f-9c35-9bb7fcfb0426 exists true
2019-06-12T18:04:28.4497561Z ...configuring AWS credentials from service endpoint '5a441e49-72f1-447f-9c35-9bb7fcfb0426'
2019-06-12T18:04:28.4497708Z ...endpoint defines standard access/secret key credentials
2019-06-12T18:04:28.4497857Z Configuring region for task
2019-06-12T18:04:28.4497990Z ##[debug]regionName=us-east-1
2019-06-12T18:04:28.4498135Z ...configured to use region us-east-1, defined in task.
2019-06-12T18:04:28.4498391Z ##[debug]AWS headBucket request ID: undefined
2019-06-12T18:04:28.4498568Z ##[debug]task result: Failed
2019-06-12T18:04:28.4549784Z ##[error]Error: Bucket targetbucketobscured does not exist
2019-06-12T18:04:28.4558810Z ##[debug]Processed: ##vso[task.issue type=error;]Error: Bucket targetbucketobscured does not exist
2019-06-12T18:04:28.4559681Z ##[debug]Processed: ##vso[task.complete result=Failed;]Error: Bucket targetbucketobscured does not exist
2019-06-12T18:04:28.4589356Z ##[section]Finishing: S3 Download: targetbucketobscured

**Comment by daniloreis-cit** [comment] 2019-06-12 20:01
2019-06-12T18:21:23.7375489Z ##[debug]Evaluating condition for step: 'Push Image: clusterdevhml'
2019-06-12T18:21:23.7375871Z ##[debug]Evaluating: succeeded()
2019-06-12T18:21:23.7375996Z ##[debug]Evaluating succeeded:
2019-06-12T18:21:23.7376171Z ##[debug]=> True
2019-06-12T18:21:23.7376352Z ##[debug]Result: True
2019-06-12T18:21:23.7376527Z ##[section]Starting: Push Image: clusterdevhml
2019-06-12T18:21:23.7379249Z ==============================================================================
2019-06-12T18:21:23.7379322Z Task         : Amazon ECR Push
2019-06-12T18:21:23.7379375Z Description  : Push a Docker image to an Amazon Elastic Container Registry on AWS
2019-06-12T18:21:23.7379446Z Version      : 1.2.0
2019-06-12T18:21:23.7379493Z Author       : Amazon Web Services
2019-06-12T18:21:23.7379626Z Help         : Please refer to [Amazon Elastic Container Registry](https://docs.aws.amazon.com/AmazonECR/latest/userguide/) documentation for working with this service.

More information on this task can be found in the [task reference](https://docs.aws.amazon.com/vsts/latest/userguide/ecr-pushimage.html).

####Task Permissions
This task requires permissions to call the following AWS service APIs (depending on selected task options, not all APIs may be used):
* ecr:DescribeRepositories
* ecr:CreateRepository
* ecr:GetAuthorizationToken
2019-06-12T18:21:23.7379782Z ==============================================================================
2019-06-12T18:21:23.9529977Z ##[debug]agent.TempDirectory=/var/devops/agent1/_work/_temp
2019-06-12T18:21:23.9545401Z ##[debug]loading inputs and endpoints
2019-06-12T18:21:23.9549121Z ##[debug]loading INPUT_AWSCREDENTIALS
2019-06-12T18:21:23.9554674Z ##[debug]loading INPUT_REGIONNAME
2019-06-12T18:21:23.9556246Z ##[debug]loading INPUT_IMAGESOURCE
2019-06-12T18:21:23.9556906Z ##[debug]loading INPUT_SOURCEIMAGENAME
2019-06-12T18:21:23.9557616Z ##[debug]loading INPUT_SOURCEIMAGETAG
2019-06-12T18:21:23.9558238Z ##[debug]loading INPUT_REPOSITORYNAME
2019-06-12T18:21:23.9558892Z ##[debug]loading INPUT_PUSHTAG
2019-06-12T18:21:23.9559586Z ##[debug]loading INPUT_AUTOCREATEREPOSITORY
2019-06-12T18:21:23.9560149Z ##[debug]loading INPUT_LOGREQUEST
2019-06-12T18:21:23.9560785Z ##[debug]loading INPUT_LOGRESPONSE
2019-06-12T18:21:23.9562243Z ##[debug]loading ENDPOINT_AUTH_d60f1f75-7775-46af-a9e1-769d229f6f72
2019-06-12T18:21:23.9562737Z ##[debug]loading ENDPOINT_AUTH_SCHEME_d60f1f75-7775-46af-a9e1-769d229f6f72
2019-06-12T18:21:23.9563466Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_d60f1f75-7775-46af-a9e1-769d229f6f72_USERNAME
2019-06-12T18:21:23.9563852Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_d60f1f75-7775-46af-a9e1-769d229f6f72_PASSWORD
2019-06-12T18:21:23.9565583Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2019-06-12T18:21:23.9566900Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2019-06-12T18:21:23.9567476Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2019-06-12T18:21:23.9571738Z ##[debug]loading SECRET_POSTGRES_LIQUIBASE_PASSWORD
2019-06-12T18:21:23.9572422Z ##[debug]loaded 18
2019-06-12T18:21:23.9584202Z ##[debug]Agent.ProxyUrl=undefined
2019-06-12T18:21:23.9585268Z ##[debug]Agent.CAInfo=undefined
2019-06-12T18:21:23.9585457Z ##[debug]Agent.ClientCert=undefined
2019-06-12T18:21:23.9585673Z ##[debug]Agent.SkipCertValidation=undefined
2019-06-12T18:21:24.0335310Z ##[debug]check path : /var/devops/agent1/_work/_tasks/ECRPushImage_467d1870-1a00-4755-b00d-9642129fe759/1.2.0/task.json
2019-06-12T18:21:24.0336048Z ##[debug]adding resource file: /var/devops/agent1/_work/_tasks/ECRPushImage_467d1870-1a00-4755-b00d-9642129fe759/1.2.0/task.json
2019-06-12T18:21:24.0336442Z ##[debug]system.culture=en-US
2019-06-12T18:21:24.0352213Z ##[debug]logRequest=false
2019-06-12T18:21:24.0353554Z ##[debug]logResponse=false
2019-06-12T18:21:24.0354910Z ##[debug]Agent.ProxyUrl=undefined
2019-06-12T18:21:24.0355726Z ##[debug]imageSource=imagename
2019-06-12T18:21:24.0356767Z ##[debug]repositoryName=myserviceimage
2019-06-12T18:21:24.0357159Z ##[debug]pushTag=desenvolvimento
2019-06-12T18:21:24.0357788Z ##[debug]autoCreateRepository=true
2019-06-12T18:21:24.0358262Z ##[debug]outputVariable=null
2019-06-12T18:21:24.0359370Z ##[debug]sourceImageName=myserviceimage
2019-06-12T18:21:24.0359833Z ##[debug]sourceImageTag=desenvolvimento
2019-06-12T18:21:24.0378567Z Configuring credentials for task
2019-06-12T18:21:24.0379668Z ##[debug]awsCredentials=d60f1f75-7775-46af-a9e1-769d229f6f72
2019-06-12T18:21:24.0382057Z d60f1f75-7775-46af-a9e1-769d229f6f72 exists true
2019-06-12T18:21:24.0382459Z ##[debug]d60f1f75-7775-46af-a9e1-769d229f6f72 exists true
2019-06-12T18:21:24.0382916Z ...configuring AWS credentials from service endpoint 'd60f1f75-7775-46af-a9e1-769d229f6f72'
2019-06-12T18:21:24.0383017Z ...endpoint defines standard access/secret key credentials
2019-06-12T18:21:24.0397290Z Configuring region for task
2019-06-12T18:21:24.0399402Z ##[debug]regionName=us-east-1
2019-06-12T18:21:24.0399920Z ...configured to use region us-east-1, defined in task.
2019-06-12T18:21:24.0458603Z ##[debug]which 'docker'
2019-06-12T18:21:24.0462766Z ##[debug]found: '/usr/bin/docker'
2019-06-12T18:21:24.0463152Z ##[debug]which 'docker'
2019-06-12T18:21:24.0463503Z ##[debug]found: '/usr/bin/docker'
2019-06-12T18:21:24.0471909Z Pushing image 'myserviceimage:desenvolvimento'
2019-06-12T18:21:24.0472716Z Obtaining authentication token for ECR login
2019-06-12T18:21:24.0611948Z ##[debug]AWS getAuthorizationToken request ID: undefined
2019-06-12T18:21:24.0616561Z ##[debug]task result: Failed
2019-06-12T18:21:24.0663316Z ##[error]Error: Failed to obtain authorization token to log in to ECR, error: CredentialsError: Missing credentials in config
2019-06-12T18:21:24.0670335Z ##[debug]Processed: ##vso[task.issue type=error;]Error: Failed to obtain authorization token to log in to ECR, error: CredentialsError: Missing credentials in config
2019-06-12T18:21:24.0670861Z ##[debug]Processed: ##vso[task.complete result=Failed;]Error: Failed to obtain authorization token to log in to ECR, error: CredentialsError: Missing credentials in config
2019-06-12T18:21:24.0671597Z ##[section]Finishing: Push Image: myimage

**Comment by sharkguto** [comment] 2019-06-12 20:09
I am getting the same error here.... s3,ecr,ec2,elb,... all operations using the credentials is crashing

```
####Task Permissions
This task requires permissions to call the following AWS service APIs (depending on selected task options, not all APIs may be used):
* ecr:DescribeRepositories
* ecr:CreateRepository
* ecr:GetAuthorizationToken
2019-06-12T18:04:03.7503903Z ==============================================================================
2019-06-12T18:04:04.1836978Z Configuring credentials for task
2019-06-12T18:04:04.1840287Z cdd8fe8f-3684-4b04-941d-187f67c39e0b exists true
2019-06-12T18:04:04.1841675Z ...configuring AWS credentials from service endpoint 'cdd8fe8f-3684-4b04-941d-187f67c39e0b'
2019-06-12T18:04:04.1841874Z ...endpoint defines standard access/secret key credentials
2019-06-12T18:04:04.1859720Z Configuring region for task
2019-06-12T18:04:04.1860579Z ...configured to use region us-east-1, defined in task.
2019-06-12T18:04:04.1983467Z Pushing image 'xxxxx-backend:latest'
2019-06-12T18:04:04.1983859Z Obtaining authentication token for ECR login
2019-06-12T18:04:04.2265053Z ##[error]Error: Failed to obtain authorization token to log in to ECR, error: CredentialsError: Missing credentials in config
2019-06-12T18:04:04.2276071Z ##[section]Finishing: Push Image: latest
```

**Comment by hunterwerlla** [comment] 2019-06-12 20:19
We have a hotfix to fix this issue: https://github.com/aws/aws-vsts-tools/pull/252 we will be rolling it out as fast as possible

**Comment by kiiadi** [comment] 2019-06-12 20:21
Duplicate of #251

**Closed by kiiadi** 2019-06-12 20:21 UTC

**Comment by hunterwerlla** [comment] 2019-06-12 21:29
@jbaacke We just released version 1.3.0, can you verify that it fixes your issue?

**Comment by validusrecruitment** [comment] 2019-06-13 12:39
Yes - it fixed my issue with an ECR push failing (same as above).

**Comment by jlausolutions** [comment] 2019-06-13 17:55
When running via Azure Devops, the task is still using version 1.2.0:

![image](https://user-images.githubusercontent.com/40897082/59455707-c3495880-8de2-11e9-9800-d778d08a3c00.png)

The only option when defining the task is to set the major version (1.X.X).

**Comment by validusrecruitment** [comment] 2019-06-13 17:58
@jlausolutions Make sure you kick off a new build or release otherwise DevOps seems to cache all the settings from the old one.

**Comment by jlausolutions** [comment] 2019-06-13 18:54
I've tried the following: 
1. Cloning the existing "Build"
2. Queueing the build using a new Git commit and branch
3. Creating a new build from scratch, adding a fresh "S3 Upload" task

In all cases, the build is failing and showing that version 1.2.0 is still being used.

**Comment by validusrecruitment** [comment] 2019-06-13 19:01
@jlausolutions I'm assuming your NOT using on-prem?  Check your extensions to be sure the 1.3.0 version has been installed:

![image](https://user-images.githubusercontent.com/32070663/59459998-0e1b9e00-8dec-11e9-80d5-0b48ccdfa232.png)

**Comment by hunterwerlla** [comment] 2019-06-13 19:50
@jlausolutions I've encountered situations where sometimes TFS refuses to update the plugin, the fastest way for me to fix it was to uninstall the plugin then reinstall it. It should leave all of your build tasks in tact since they are based on of GUID and not version.
