### ISSUE TITLE
system Manager Run command  Fails with AccessDeniedException after 1.2.0 release

### ISSUE THREAD

**Issue by isiddiq3** [aws/aws-vsts-tools#247] opened 2019-06-12 19:21 UTC
system Manager Run command  Fails with AccessDeniedException after 1.2.0 release, i have verified the Assume Role has permissions, but the task fails, Manual run from the console works fine.

Your Environment

Azure Devops Cloud
Amazon System Manager Run command
Version: 1.2.0

**Comment by hunterwerlla** [comment] 2019-06-12 20:19
We have a hotfix to fix this issue: https://github.com/aws/aws-vsts-tools/pull/252 we will be rolling it out as fast as possible

**Comment by kiiadi** [comment] 2019-06-12 20:22
Duplicate of #251 please use that for tracking.

**Closed by kiiadi** 2019-06-12 20:22 UTC
