### ISSUE TITLE
S3 Upload Task is missing 

### ISSUE THREAD

**Issue by patrmci** [aws/aws-vsts-tools#23] opened 2017-10-06 17:38 UTC
After installing the AWS toolkit on the TFS server (2015 update 3) the only AWS task that shows up in the AWS CLI.  None of the other tasks are displayed as available tasks for the build.

**Comment by steveataws** [comment] 2017-10-09 15:12
I wondered if this could be down to the agent version, but all of the tasks except the PowerShell one have minimum agent value set the same - 1.91.0, so that would appear to rule it out. The CLI task is also attributed the same as the others, category = deploy and visibility=build & release.

Can you give us some more details of the type of build you are trying to use the tasks in?

**Comment by patrmci** [comment] 2017-10-09 19:54
This is .NET Build process.  There are 3 steps, NuGet Installer, Visual Studio Build and Visual Studio Test task.   I need to get the binaries up to S3 for deployment.  I should mention that this is S3 Gov cloud also.

When I setup the Service Endpoint, there is no entry for endpoint or account type.  Also, I do not see any indication that there is a successful connection or not.  This might be in the specific S3 Upload Test? 

Could security or a firewall be an issue?

Is there anyway to verify that the S3 Upload task was in fact installed?

**Comment by steveataws** [comment] 2017-10-10 15:14
Short of it appearing in the available tasks to add to a build or release definition, I can't think of a way to verify install. I don't think use of GovCloud is an issue since you haven't even been able to use a service yet, which is where the region information would be used.

The fact that you only see one task, and no endpoint type, feels like you have a corrupted install somehow. Assuming you haven't already, can you try uninstalling the extension and then re-downloading and installing? And do you have a VSTS account that you could do the same with? In the meantime I'll try and setup a 2015 TFS instance and see if I can repro.

**Comment by patrmci** [comment] 2017-10-10 15:24
OK.  We'll do an install with a fresh download of the plugin.

I'll see if I can setup a VSTS and give it a try there.

**Comment by steveataws** [comment] 2017-10-10 16:49
I've reproduced your issue on a TFS2015 Update 4 install, although in my case I see the AWS CLI task and the AWS service endpoint type is listed. None of the other tasks appear, even though all the tasks are set to the same category ("Deploy") and visibility ("Build" and "Release"). The tasks, with the exception of the PowerShell one, all have the same minimum agent version too, 1.91.0

Taking the exact same extension package and installing it into a TFS2017 Update 1 instance, all tasks show up, and the endpoint type too. As a test, I switched the task category settings to Build (per the schema reference [here](https://docs.microsoft.com/en-us/vsts/extend/develop/build-task-schema) and reinstalled an updated package to the 2015 instance but there was no change.

Continuing to look into the issue, but right now I have no new ideas to test out.

**Comment by patrmci** [comment] 2017-10-10 18:04
We just uninstalled, downloaded the plugin again and reinstalled and we are
getting the same results - only the AWS CLI task is shown.  So, same
results.

Thanks!

**Comment by patrmci** [comment] 2017-10-13 18:23
Just curious if any progress has been made on figuring out why the other
tasks do not show up.

Thanks!
Patrick

**Comment by steveataws** [comment] 2017-10-16 17:30
Nothing yet, the task manifests all check out against the latest schemas so it's unknown why TFS2015 isn't seeing them all, especially as the one it does show has the same manifest data as those it does not.

I'm going to have to raise an issue with Microsoft to see if they have any ideas and will report back.

**Comment by kellydoesmath** [comment] 2017-10-19 18:23
I am also using TFS 2015 SP 4 and encountered this issue. Was searching for solution, but appears you have reproduced the exact same issue.

**Comment by steveataws** [comment] 2017-10-20 16:43
[Another user](https://github.com/aws/aws-vsts-tools/issues/33) has pinpointed the issue. We're working to find a resolution to our use of the agent.tempDirectory variable (introduced in agent version 2.115) so that we can lower the minimum agent version of the PowerShell script task. It turns out that when the TFS install mechanism sees this higher requirement, it drops the task and all subsequent ones from the install - leaving only the CLI task, as it is listed first in the manifest.

**Comment by patrmci** [comment] 2017-10-20 18:26
That is great news, Steve!  Thanks for your efforts on this.

**Comment by steveataws** [comment] 2017-10-23 21:55
v1.0.8 has now been released, which downgrades the minimum agent version for the PowerShell task to match the others, and adapts to the presence of the Agent.TempDirectory variable based on the installed agent version. This resolves the missing tasks issue so far as we can tell from our TFS2015 install setup.

Resolving issue; feel free to reopen if you still encounter issues.

**Closed by steveataws** 2017-10-23 21:55 UTC
Labels: question

**Comment by patrmci** [comment] 2017-10-24 23:37
Hi Steve,

Thank you very much!   We'll download the new version and give it a try.

Patrick
