### ISSUE TITLE
CredentialsError: Missing credentials in config after update to aws-vsts-tools 1.2.0

### ISSUE THREAD

**Issue by thepharcyde2016** [aws/aws-vsts-tools#248] opened 2019-06-12 19:32 UTC
**Describe the bug**

 message: 'Could not load credentials from any providers'

**To reproduce**

In vsts the release definition task AWS CloudFormation Create/Update Stack
is having issues pulling AWS Credentials, this is causing task to fail.  

error: 
2019-06-12T18:14:39.1597700Z Change set creation request failed with error: 'Missing credentials in config' { CredentialsError: Missing credentials in config
2019-06-12T18:14:39.1597700Z     at IncomingMessage.<anonymous> (F:\_a\1\_w\_tasks\CloudFormationCreateOrUpdateStack_7ef7cdfa-aa45-42c5-93c8-d7603643dd99\1.2.0\CloudFormationCreateOrUpdateStack.js:1:16536)
2019-06-12T18:14:39.1597700Z     at emitNone (events.js:91:20)
2019-06-12T18:14:39.1597700Z     at IncomingMessage.emit (events.js:185:7)
2019-06-12T18:14:39.1597700Z     at endReadableNT (_stream_readable.js:974:12)
2019-06-12T18:14:39.1597700Z     at _combinedTickCallback (internal/process/next_tick.js:80:11)
2019-06-12T18:14:39.1597700Z     at process._tickDomainCallback (internal/process/next_tick.js:128:9)
2019-06-12T18:14:39.1597700Z   message: 'Missing credentials in config',
2019-06-12T18:14:39.1597700Z   retryable: false,
2019-06-12T18:14:39.1597700Z   time: 2019-06-12T18:14:39.159Z,
2019-06-12T18:14:39.1597700Z   code: 'CredentialsError',
2019-06-12T18:14:39.1597700Z   originalError: 
2019-06-12T18:14:39.1597700Z    { message: 'Could not load credentials from any providers',
2019-06-12T18:14:39.1597700Z      retryable: false,
2019-06-12T18:14:39.1597700Z      time: 2019-06-12T18:14:39.159Z,
2019-06-12T18:14:39.1597700Z      code: 'CredentialsError' } }
2019-06-12T18:14:39.1753930Z ##[error]CredentialsError: Missing credentials in config

**Expected behavior**

**Screenshots**

**Your Environment**
 - VSTS or Azure Devops (on-prem or cloud based?):  Azure Devops Cloud
 - VSTS or Azure Devops version: 
 - AWS VSTS Tools version: 1.2.0

This was working in version 1.1.8

**Comment by jlausolutions** [comment] 2019-06-12 19:44
Seeing the same issue.

**Your Environment**

Azure Devops Cloud
Amazon S3 Upload
Version: 1.2.0

Note that there are other tasks (AWS CLI 1.2.0) that are running  successfully.

**Comment by thepharcyde2016** [comment] 2019-06-12 19:47
We have multiple aws accounts but we have a separate user for each account with dedicated api keys per account.  Also seeing this issue on Amazon ECR Push Task: 

error: ##[error]Error: Failed to obtain authorization token to log in to ECR, error: CredentialsError: Missing credentials in config

**Comment by jabberwik** [comment] 2019-06-12 19:48
Seeing the same issue with the SSM Get Parameter Task

**Comment by hunterwerlla** [comment] 2019-06-12 20:19
We have a hotfix to fix this issue: https://github.com/aws/aws-vsts-tools/pull/252 we will be rolling it out as fast as possible

**Comment by kiiadi** [comment] 2019-06-12 20:22
Duplicate of #251 please use that for tracking.

**Closed by kiiadi** 2019-06-12 20:22 UTC
