### ISSUE TITLE
Lambda Tags Not Applied

### ISSUE THREAD

**Issue by StephenRSkinner** [aws/aws-vsts-tools#270] opened 2019-06-28 22:26 UTC
**Describe the bug**
Setting tags on the Deploy Lambda task does not set the tags on the lambda. I'm working with an existing lambda, so not sure if it's an update issues.

**To reproduce**
1. Add a tag to an existing Deploy Lambda task.
2. Execute a release.

**Expected behavior**
The tag should be applied to the lambda.

**Your Environment**
TFS 2018 On-Premise

**Comment by hunterwerlla** [comment] 2019-07-02 15:09
I'll see if I can reproduce

**Comment by hunterwerlla** [comment] 2019-07-03 20:42
It looks like tags are not being added on update, I will fix this

**Comment by hunterwerlla** [comment] 2019-08-21 19:40
This is now fixed in the 1.5 release

**Closed by hunterwerlla** 2019-08-21 19:40 UTC
Labels: bug, pending-release
