### ISSUE TITLE
[TFS 2015] AWS Endpoint configuration requires values in all fields.

### ISSUE THREAD

**Issue by kellydoesmath** [aws/aws-vsts-tools#35] opened 2017-10-30 20:33 UTC
AWS VSTS 1.0.12
TFS 2015 SP4

The endpoint configuration requires values in all fields including the optional fields. Adding a role-name then breaks using the build/release steps because a valid role must be available for the IAM user to assume:

2017-10-30T20:09:01.6962270Z Configuring task to use role-based credentials.
2017-10-30T20:09:02.2615620Z ##[error]The security token included in the request is invalid.

![addawsconnection](https://user-images.githubusercontent.com/15160546/32194189-de78af72-bd76-11e7-9e92-d5ca0f9aa32a.png)

**Comment by kellydoesmath** [comment] 2017-10-30 22:24
I downgraded to AWS VSTS 1.0.7 and created the endpoint using just the first 3 parameters. Then upgraded tools back to 1.0.12 allowing the use of the other tasks. The 1.0.12 agent does not allow the endpoint to be created without populating all the fields.

**Comment by steveataws** [comment] 2017-10-30 23:15
That's odd and not the experience for me on any of my test systems - the manifest declares all fields except the name, access and secret keys to be optional. I'll take a look and get back to you asap.

**Comment by steveataws** [comment] 2017-10-31 02:44
I've reproduced with a clean project on my TFS2015 update 4 system and am investigating further. It appears that the optional setting flags for the endpoint type, although obeyed in TFS2017 and VSTS, are ignored in TFS2015. I think my testing in 2015 was actually working with existing endpoints with tests to create new ones being done in 2017/VSTS, so apologies for the inconvenience.

I'll get back to you with an update asap.

**Comment by kellydoesmath** [comment] 2017-10-31 03:03
I found that if you attempt to edit the existing endpoint, this bug is encountered. I downgraded to an earlier version of the tools to see if I could load in credentials. That brings me back to the older problem on only having the CLI task available.

**Comment by steveataws** [comment] 2017-10-31 03:42
If you use the older version to set up the endpoints you need, then install the latest version (to fix the tasks disappearing due to the agent version problem) does that at least get you up and running on your install? I've found a mechanism that allows us to show different authentication type panes that I think will work but need some time to dig into the details and verify.

**Comment by kellydoesmath** [comment] 2017-10-31 04:30
Yes, that is what I did to move forward.

**Comment by steveataws** [comment] 2017-11-01 18:48
We've reached out to Microsoft to try and determine why the optional field attribution is obeyed in TFS2017/VSTS, but ignored in TFS2015 and also to determine how we can best update the endpoint definition to match what is done for other endpoint types (like Azure for example) where the endpoint dialog can contain multiple different sets of auth parameters. This latter approach seems like how we want to progress given we also want to add support for EC2 instance profile credentials.

I'll update the issue when I know more.

**Comment by agos-jwb** [comment] 2017-11-08 17:28
I am using TFS 2015 and am also running into this issue. Unfortunately, I had not installed aws-vsts-tools before the current version and so am unable to create endpoints. Is it possible to get the 1.0.7 version of the vsix file so I can downgrade and create the endpoint?

**Comment by steveataws** [comment] 2017-11-12 18:41
Apologies for the delay in responding, I hadn't noticed the comment. I'll locate the 1.0.7 version when I get into the office Monday and post a link to it here.

**Comment by steveataws** [comment] 2017-11-13 17:02
A special build for TFS2015 is now available [here](https://sdk-for-net.amazonwebservices.com/latest/amazonwebservices.aws-vsts-tools-1.0.12-tfs2015.vsix). We'll keep this version available until we resolve the issue of TFS not recognizing the optional attribution on the new fields we added to support assume role credentials.

This build matches our current public release but has had the new assume role options removed from the AWS endpoint type. Testing on my TFS2015 update 4 setup worked with creating new endpoints as well as loading endpoint data from previous releases, but if you hit any issues let me know and I'll address them asap.

**Comment by steveataws** [comment] 2018-07-18 15:38
Updated title to reflect this is an issue with TFS 2015, we have not reproduced it on any other version. The problem seems to be a bug in TFS itself which I don't think will ever be fixed. 

Leaving issue open for a while longer so the link to download the special build of the tools remains visible although it is called out in the marketplace readme too.

**Comment by hunterwerlla** [comment] 2019-06-24 20:32
Closing, special build is available, but there will be no more updates for TFS2015

**Closed by hunterwerlla** 2019-06-24 20:32 UTC
Labels: bug
