### ISSUE TITLE
Problem with 1.2.0 version

### ISSUE THREAD

**Issue by codefc** [aws/aws-vsts-tools#251] opened 2019-06-12 19:52 UTC
**Describe the bug**
About two hours ago, my builds with dependency of the AWS ERC Push present the follow error:

"Error: Failed to obtain authorization token to log in to ECR, error: CredentialsError: Missing credentials in config"

But, i tested the connection with the AWS ECR manually and the credentials works fine.

Now I can't generate builds of my application because I depend of this task.

**Your Environment**
 - Azure Devops - cloud based: 
 - VSTS or Azure Devops version: 
 - AWS VSTS Tools version:

**Comment by sharkguto** [comment] 2019-06-12 19:55
same here :+1:

**Comment by deboraadorni** [comment] 2019-06-12 19:57
Same here!

**Comment by thepharcyde2016** [comment] 2019-06-12 19:58
Same

**Comment by neilgroat** [comment] 2019-06-12 20:11
same here!

**Comment by oren-beeri** [comment] 2019-06-12 20:12
Same here!!!

**Comment by eflorespalma** [comment] 2019-06-12 20:15
Same here!!!

**Comment by hunterwerlla** [comment] 2019-06-12 20:19
We have a hotfix to fix this issue: https://github.com/aws/aws-vsts-tools/pull/252 we will be rolling it out as fast as possible

**Comment by sharkguto** [comment] 2019-06-12 20:28
@hunterwerlla thank you !

**Comment by thepharcyde2016** [comment] 2019-06-12 20:49
Thanks!

**Comment by neilgroat** [comment] 2019-06-12 20:51
Thank you for the quick response!

**Comment by bgkyer** [comment] 2019-06-12 20:55
Thanks!

**Comment by hunterwerlla** [comment] 2019-06-12 21:26
@codefc We just released version 1.3.0, can you verify that it fixes your issue?

**Comment by neilgroat** [comment] 2019-06-12 21:33
Confirmed for me.

My pipeline is now succeeding and I have my newly built image uploaded to ECR

Thanks!

**Comment by jabberwik** [comment] 2019-06-12 21:44
Working for me as well. Thanks for the quick turnaround!

**Comment by isiddiq3** [comment] 2019-06-12 21:51
Works for me as well, Thanks @hunterwerlla

**Comment by jossaq** [comment] 2019-06-12 21:58
Can you please update the changelog?

**Comment by bgkyer** [comment] 2019-06-12 22:08
Confirmed works now. Thanks!

**Comment by pdamasceno** [comment] 2019-06-12 22:15
Was having the same problem and confirm that it is working now. Thanks.

**Comment by eflorespalma** [comment] 2019-06-12 22:18
It's working now. Thanks

**Comment by hunterwerlla** [comment] 2019-06-12 22:20
Closing as it looks like the issue is now released and resolved

**Closed by hunterwerlla** 2019-06-12 22:20 UTC
Labels: bug

**Comment by mikelindenmuth** [comment] 2019-06-12 22:22
confirmed working as well. thanks for the quick turnaround @hunterwerlla!

**Comment by johniwasz** [comment] 2019-06-17 13:21
I'm using Azure DevOps and in the Lambda build task that was working prior to version 1.2.0 _and_ version 1.3.0, I'm getting the following error in a package lambda task:

The task also requires permissions to upload your Lambda function or serverless application content to the specified Amazon S3 bucket. Depending on the size of the application bundle, either putObject or the S3 multi-part upload APIs may be used.
==============================================================================
Processing Lambda project at /home/vsts/work/1/s/src/[PROJECTNAMEREDACTED]
Reading existing aws-lambda-tools-defaults.json
Clearing out profile [PROFILENAMEREDACTED] so task credentials will be used.
Configuring credentials for task
No credentials configured.The task will attempt to use credentials found in the build host environment.
Configuring region for task
...configured to use region us-east-1, defined in task.
Beginning dotnet restore
Path to tool: /usr/bin/dotnet
[command]/usr/bin/dotnet restore
  Restore completed in 48.57 ms for /home/vsts/work/1/s/src/[PROJNAMEREDACTED].csproj.
Beginning Lambda Deployment
Performing package-only build of function, output package will be placed in /home/vsts/work/1/a/packageddeployment.zip
Path to tool: /usr/bin/dotnet
[command]/usr/bin/dotnet lambda package -o /home/vsts/work/1/a/packageddeployment.zip --region us-east-1 -fn SbsStoryEngine -fh [HANDLERREDACTED] --function-role [ROLEREDACTED] --function-memory-size 1024 --function-timeout 60 --disable-interactive true --no-build
No executable found matching command "dotnet-lambda"
##[error]Error: The process '/usr/bin/dotnet' failed with exit code 1
##[section]Finishing: Package  [LAMBDANAMEREDACTED]


I installed lambda tools in a prior task:

##[section]Starting: Install Global Amazon.Lambda.Tools
==============================================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.153.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
==============================================================================
[command]/usr/bin/dotnet tool install Amazon.Lambda.Tools -g
Since you just installed the .NET Core SDK, you will need to logout or restart your session before running the tool you installed.
You can invoke the tool using the following command: dotnet-lambda
Tool 'amazon.lambda.tools' (version '3.2.3') was successfully installed.
##[section]Finishing: Install Global Amazon.Lambda.Tools

----------------

The build task and unit testing tasks complete, but the Lambda packaging task fails with the dotnet-lambda tool not found.
