### ISSUE TITLE
Lambda Invoke function doesn't honor timepout configuration

### ISSUE THREAD

**Issue by chiupinchen** [aws/aws-vsts-tools#130] opened 2018-11-28 21:21 UTC
Our team has seen one issue that seems AWS Lambda Invoke Function doesn't take the timeout configuration under Control Options into runtime behavior. 
![image](https://user-images.githubusercontent.com/1776553/49182668-81facb00-f320-11e8-8e9b-1a7de3f0466b.png)
I changed this to be 20 minutes (even though default value 0 is indicated as infinite) and still got timeout error. Looks to me it has been retrying 3 times so it times out the "step" in 8 minutes but the error says "Connection timed out after 120000ms", which is 2 minutes.

![image](https://user-images.githubusercontent.com/1776553/49182827-e9b11600-f320-11e8-9c03-6a3fcd2edae8.png)

Can someone help me on this? Thank you!

**Comment by steveataws** [comment] 2018-11-28 22:21
The timeout field on the task isn't related to the service call the task makes to Lambda but is a built-in control option that's available for all tasks. 

I've never had reason to change that option so am not 100% familiar with how it works in the environment,or where the  retry logic is handled, but are you sure your build has outbound connectivity? Do any of the other tasks that make network calls fail or is it just this one?  Assuming connectivity is OK, how long does your Lambda function take to run on average?

**Comment by chiupinchen** [comment] 2018-11-28 23:47
Yes, the outbound connectivity is good and I see logs on the Lambda side. Our lambda runs about 3~4 minutes. An enhancement that I can pass in the timeout and retry times would be very helpful.

**Comment by steveataws** [comment] 2018-12-03 22:59
There's no timeout option on the api call the task uses to invoke a function, but did you configure a timeout when you created the function in the first instance? You can specify up to 900 seconds (which should be ample for your 3-4min runtime) - https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html

I suspect from the output that the connection is being closed and so we need to add a keep-alive to the request but figured it was worth checking if you had configured a timeout on function creation. I don't think that a keep-alive option would necessarily need any task configuration options (since we know a Lambda function cannot run for more than 900secs anyway, which gives us an upper limit).

**Comment by chiupinchen** [comment] 2018-12-06 19:40
We do configure the function to run up to 900 seconds. The timeout happens in the AWS Lambda Invoke Function side on VSTS. Our current work around is to use AWS cli with infinite timeout:

aws lambda invoke **--cli-connect-timeout 0** --cli-read-timeout 0 --function-name $(FunctionName) --log-type Tail --payload $(payload) outputfile.txt

![image](https://user-images.githubusercontent.com/1776553/49607650-3e294680-f95c-11e8-8cee-0cea064f251e.png)

**Comment by lslaslo** [comment] 2019-03-30 05:39
We have been able to reproduce this and see the same, "Connection timed out after 120000ms" in VSTS. The function is configured to run up to 15 minutes (900 seconds) in AWS.

**Comment by hunterwerlla** [comment] 2019-11-04 21:08
This is fixed with honoring timeouts in 1.2.0. Previously, the logic was incorrect.

**Closed by hunterwerlla** 2019-11-04 21:08 UTC
Labels: needs-repro
