### ISSUE TITLE
get outputs when using the cloudformation create/update task

### ISSUE THREAD

**Issue by jeffrey-opdam** [aws/aws-vsts-tools#106] opened 2018-09-17 19:27 UTC
Hi guys,

When using the cloudformation create/update task, you will get the stackid as an output variable.
Is it also possible to get the outputs as defined in the yml file?

`
Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref EC2Instance
  AZ:
    Description: Availability Zone of the newly created EC2 instance
    Value: !GetAtt 
      - EC2Instance
      - AvailabilityZone
  PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value: !GetAtt 
      - EC2Instance
      - PublicDnsName
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt 
      - EC2Instance
      - PublicIp
`

**Comment by steveataws** [comment] 2018-09-26 17:06
Apologies for the delay in responding; combination of vacations and team focus elsewhere for the moment :-)

It's certainly possible, how would you want to consume the outputs? As a series of build variables, or a formatted blob of yaml/json that you'd need to parse?

**Comment by jeffrey-opdam** [comment] 2018-09-26 17:10
As a series of build variables, so I have the fqdn name, which I later can use in my deployment

**Comment by steven-cuthill-otm** [comment] 2018-09-28 10:06
Build vars would be awesome but also json output would be handy too, could help with cross-region workloads.

**Comment by steveataws** [comment] 2018-10-02 19:53
Ok, I'll see what we can get done but I can't promise any specific ETA right now. Of course, we're also always happy to take pull requests!

**Comment by steven-cuthill-otm** [comment] 2018-10-02 20:27
Tempted to start contributing, is there a into guid for developing on the VSTS / ADO platform ?

**Comment by steveataws** [comment] 2018-10-03 15:54
We don't (yet) have a contributing guide in the repo but all our tasks are reasonably standardized in how we put them together so extending one to add some new parameters is relatively easy. The tricky bit is in testing; we used to be able to use a launch config entry in VSCode during development to simulate supply of the credentials and parameters into the task but with recent updates we're finding this no longer works and haven't had time to find the root cause yet. We (at AWS) are currently reliant on a Team Foundation Server instance running integration tests to verify our changes, which obviously isn't suitable for long term open source contributions.

The general development guidelines for the host environment can be found [here](https://docs.microsoft.com/en-us/azure/devops/extend/overview?view=vsts).

In the absence of a formal contributing doc and unit test setup, I'd be happy to help guide a contribution if you want to give it a try (and also help with testing).

**Comment by manishap411** [comment] 2019-05-30 02:09
Has this change been released? or is there a timeline for when this could roll out? Thanks!

**Comment by hunterwerlla** [comment] 2019-06-12 17:54
This is fixed as of the 1.2.0 release we just did, @manishap411 @jeffrey-opdam

**Closed by hunterwerlla** 2019-06-12 17:54 UTC
Labels: feature-request, pending-release
